import React from 'react';
import Link from 'next/link';
import style from './navigation.module.scss';
import { GetDealTypeUrl } from 'helpers/urlHelper';
import { VehicleTypes } from 'enums/VehicleTypes';

const NavBodies = ({id, dealSelector, VehicleType}) => {

    const getDeralTypeUrlDynamic = GetDealTypeUrl(dealSelector, );
    if(VehicleType === VehicleTypes.Commercial) {
        return (
            <div id={id} className={style['panel-content']}>
                <Link passHref href={GetDealTypeUrl(dealSelector,'/body-type/small')}><a className="text-decoration-none"><span className={style['body-type-card']}><img alt="Small" width="200" height="80" className="lazyload" data-src={`${process.env.NEXT_PUBLIC_CDN}/website/static/vehicle-images/panel-small-van.png`} /><span className={style['name']}>Small</span><span className={style['description']}>e.g. Ford Connect, Peugeot Partner</span></span></a></Link>
                <Link passHref href={GetDealTypeUrl(dealSelector,'/body-type/medium')}><a className="text-decoration-none"><span className={style['body-type-card']}><img alt="Medium" width="200" height="80" className="lazyload" data-src={`${process.env.NEXT_PUBLIC_CDN}/website/static/vehicle-images/panel-medium-van.png`} /><span className={style['name']}>Medium</span> <span className={style['description']}>e.g. Citroen Dispatch, VW Transporter</span></span></a></Link>
                <Link passHref href={GetDealTypeUrl(dealSelector,'/body-type/large')}><a className="text-decoration-none"><span className={style['body-type-card']}><img alt="Large" width="200" height="80" className="lazyload" data-src={`${process.env.NEXT_PUBLIC_CDN}/website/static/vehicle-images/panel-large-van.png`} /><span className={style['name']}>Large</span> <span className={style['description']}>e.g. Peugeot Boxer, Citroen Relay</span></span></a></Link>
                <Link passHref href={GetDealTypeUrl(dealSelector,'/body-type/pickup')}><a className="text-decoration-none"><span className={style['body-type-card']}><img alt="Pickup" width="200" height="80" className="lazyload" data-src={`${process.env.NEXT_PUBLIC_CDN}/website/static/vehicle-images/panel-pickup.png`} /><span className={style['name']}>Pickup</span> <span className={style['description']}>e.g. Mitsubish L200, Ford Ranger</span></span></a></Link>
                <Link passHref href={GetDealTypeUrl(dealSelector,'/body-type/crew')}><a className="text-decoration-none"><span className={style['body-type-card']}><img alt="Crew" width="200" height="80" className="lazyload" data-src={`${process.env.NEXT_PUBLIC_CDN}/website/static/vehicle-images/panel-crew-van.png`} /><span className={style['name']}>Crew</span> <span className={style['description']}>e.g. VW Transporter, Ford Transit Custom</span></span></a></Link>
                <Link passHref href={GetDealTypeUrl(dealSelector,'/body-type/dropside')}><a className="text-decoration-none"><span className={style['body-type-card']}><img alt="Dropside" width="200" height="80" className="lazyload" data-src={`${process.env.NEXT_PUBLIC_CDN}/website/static/vehicle-images/panel-dropside.png`} /><span className={style['name']}>Dropside</span> <span className={style['description']}>e.g. Ford Transit, VW Crafter</span></span></a></Link>
                <Link passHref href={GetDealTypeUrl(dealSelector,'/body-type/luton')}><a className="text-decoration-none"><span className={style['body-type-card']}><img alt="Luton" width="200" height="80" className="lazyload" data-src={`${process.env.NEXT_PUBLIC_CDN}/website/static/vehicle-images/panel-luton-van.png`} /><span className={style['name']}>Luton</span> <span className={style['description']}>e.g. Mercedes-Benz Sprinter, Ford Transit</span></span></a></Link>
            </div>
        );
    } else {
        return (
            <div id={id} className={style['panel-content']}>
                <Link passHref href={GetDealTypeUrl(dealSelector,'/body-type/suv-crossover')}><a className="text-decoration-none"><span className={style['body-type-card']}><img alt="suv / crossover" data-src={`${process.env.NEXT_PUBLIC_CDN}/website/static/vehicle-images/panel-suv.png`} width="200" height="80" className="lazyload" /> <span className={style['name']}>SUV / Crossover</span> <span className={style['description']}>e.g.Jeep Cherokee SW, Land Rover Discovery SW</span></span></a></Link>
                <Link passHref href={GetDealTypeUrl(dealSelector,'/body-type/hatchback')}><a className="text-decoration-none"><span className={style['body-type-card']}><img alt="hatchback" data-src={`${process.env.NEXT_PUBLIC_CDN}/website/static/vehicle-images/panel-hatchback.png`} width="200" height="80" className="lazyload"/> <span className={style['name']}>Hatchback</span> <span className={style['description']}>e.g.Toyota Aygo, Vauxhall Astra</span></span></a></Link>
                <Link passHref href={GetDealTypeUrl(dealSelector,'/body-type/saloon')}><a className="text-decoration-none"><span className={style['body-type-card']}><img alt="saloon" data-src={`${process.env.NEXT_PUBLIC_CDN}/website/static/vehicle-images/panel-saloon.png`} width="200" height="80" className="lazyload" /> <span className={style['name']}>Saloon</span> <span className={style['description']}>e.g.Alfa Romeo Giulia, Ford Mondeo</span></span></a></Link>
                <Link passHref href={GetDealTypeUrl(dealSelector,'/body-type/estate')}><a className="text-decoration-none"><span className={style['body-type-card']}><img alt="estate" data-src={`${process.env.NEXT_PUBLIC_CDN}/website/static/vehicle-images/panel-estate.png`} width="200" height="80" className="lazyload"/> <span className={style['name']}>Estate</span> <span className={style['description']}>e.g.Hyundai i30 Tourer, Kia Ceed Sportswagon</span></span></a></Link>
                <Link passHref href={GetDealTypeUrl(dealSelector,'/body-type/coupe')}><a className="text-decoration-none"><span className={style['body-type-card']}><img alt="coupe" data-src={`${process.env.NEXT_PUBLIC_CDN}/website/static/vehicle-images/panel-coupe.png`} width="200" height="80" className="lazyload"/> <span className={style['name']}>Coupe</span> <span className={style['description']}>e.g.Audi A5, BMW 2 Series</span></span></a></Link>
                <Link passHref href={GetDealTypeUrl(dealSelector,'/body-type/convertible-cabriolet')}><a className="text-decoration-none"><span className={style['body-type-card']}><img alt="convertible / cabriolet" data-src={`${process.env.NEXT_PUBLIC_CDN}/website/static/vehicle-images/panel-convertible.png`} width="200" height="80" className="lazyload"/> <span className={style['name']}>Convertible / Cabriolet</span> <span className={style['description']}>e.g.Mercedes C Class, Smart ForTwo</span></span></a></Link>
                <Link passHref href={GetDealTypeUrl(dealSelector,'/body-type/mpv')}><a className="text-decoration-none"><span className={style['body-type-card']}><img alt="mpv" data-src={`${process.env.NEXT_PUBLIC_CDN}/website/static/vehicle-images/panel-mpv.png`} width="200" height="80" className="lazyload"/> <span className={style['name']}>MPV</span> <span className={style['description']}>e.g.Renault Grand Scenic, Volkswagon Touran</span></span></a></Link>
                <Link passHref href={GetDealTypeUrl(dealSelector,'/body-type/sports-car')}><a className="text-decoration-none"><span className={style['body-type-card']}><img alt="sports car" data-src={`${process.env.NEXT_PUBLIC_CDN}/website/static/vehicle-images/panel-sportscar.png`} width="200" height="80" className="lazyload"/> <span className={style['name']}>Sports Car</span> <span className={style['description']}>e.g.Abarth 124 Spider Roadster, Audi R8 Coupe</span></span></a></Link>
            </div>
        );
    }
}

export default NavBodies;