import React from 'react';
import Link from 'next/link';
import MainLayout from 'components/layout/main-layout';
import MetaHead from '../components/seo/meta';
import { GetCanonicalUrl } from 'helpers/urlHelper';
import { GetPhoneNumber } from 'helpers/helpers';
import { connect } from 'react-redux';
import { LayoutProps } from 'types/LayoutProps';

type Props = {
    isInternal: boolean;
}
const TermsConditions:LayoutProps<Props> = ({isInternal}) => {

    return (
        <>
            <MetaHead>
                <title>Terms & Conditions | Leasing Options</title>
                <meta name="description" content="Read details our Terms and Conditions." />
                <meta name="keywords" content="Personal Car Leasing, Personal Car Lease Deals, Personal Car Leasing Manchester, Contract hire" />
                <link rel="canonical" href={GetCanonicalUrl(`/terms-and-conditions`)} />
            </MetaHead>
            <section className="container-fluid py-3 py-md-5 bg-light-grey">
                <div className="container bg-white">
                    <div className="row">
                        <div className="col-24 py-3">
                            <h1>Terms and Conditions</h1>
                            <p><b>All of the provisions contained in this document are important; however, if you are a consumer entering into a regulated agreement, your special attention is drawn to clauses 3 (absolute attention relating to Data Protection and highlighted in yellow), 4, 5 and 8 below.</b></p>
                            <p><b>Please be aware that you will be required to enter into a separate finance or lease agreement with a third-party funder.
                            </b></p>
                            <h2 className="text-mint">1. Construction</h2>
                            <p>These terms and conditions, together with the documents referred to herein and Our Privacy Policy available on request or accessible via www.leasingoptions.co.uk are the terms (<strong>“Terms”</strong>) on which Leasing Options Limited (company number 02487254 and VAT Registration Number 519 4636 28) and whose registered office is at Options House, Atkin Street, Worsley, Manchester, M28 3DG (<strong>“We”</strong>), (<strong>“Us”</strong>) and (<strong>“Our”</strong>) provides its services to you.</p>
                            <p>Our services are to source a vehicle for you to lease and source the financial products and services available to enable you to do so. We are a credit broker and not a lender, our Financial Conduct Authority Firm Reference Number is 660061. We are also a member of the British Vehicle Renting and Leasing Association (<strong>“BVRLA”</strong>) and operate in accordance with its code of conduct.</p>
                            <h2 className="text-mint">2. The Website and Altering the Terms</h2>
                            <p>By accessing any part of our website, which can be accessed via <Link href="/privacy-policy" passHref><a className="text-mint">www.leasingoptions.co.uk/privacy-policy</a></Link> or any applicable mobile application run by Us (<strong>“the Website”</strong>) and/or placing an Order (as defined below) you warrant that you are at least 18 years old and legally capable of entering into binding contracts and/or authorised to do so on behalf of your organisation and agree to be bound by these Terms.</p>
                            <p>It is important to be aware that a contract will not have been formed between you and Us for the finance of a vehicle until such time as the requirements in section 4 (Prices, the Quotation and Making an Order) have been complied with below.</p>
                            <p><span>Access to the Website</span><br />You are responsible for ensuring that you have access to the Website. Please read the Terms carefully as they affect your rights and liabilities under the law. You agree that all persons who access the Website through your internet connection are aware of them. If you do not agree to be bound by the Terms you should not use or access the Website and will be unable to place an Order (as defined below).</p>
                            <p>We may temporarily or permanently modify or withdraw this Website (or any part thereof) with or without notice to you and confirm that We shall not be liable to you for any modification or withdrawal of the Website. References to the Website include any current or future version of the Website and any mobile application through which you can access the Website or Our services from time to time.</p>
                            <p><span>Information Appearing on the Website and Further Updates</span><br />We take reasonable care to ensure that all details, descriptions and prices appearing on the Website and in Our other forms of literature are correct at the time when the relevant information was entered. You should be aware that We display information supplied to Us by third parties on the Website including from CAP Automotive Limited, which receives information directly from vehicle manufacturers.</p>
                            <p>Although We aim to keep the Website and Our literature as up to date as possible, the details, description and prices appearing therein at a particular time may not always reflect the accurate position exactly at the moment you place an Order or an exact specification of your vehicle and should be used as a guide only. We accept no responsibility for any direct, indirect or consequential loss, damages, claims, compensation or expenses (<strong>“Loss”</strong>) which you suffer as a result of reliance upon information contained within the Website.</p>
                            <p>We may update these Terms from time to time for any reason including but not limited to legal or regulatory reasons or to allow the proper operation of the Website or Our processes. Any changes will apply from the date on which We begin to use them and your continued use of the Website or making of an order following that date indicates your agreement to be bound by the new Terms.</p>
                            <h2 className="text-mint">3. Making an Enquiry, Credit Searches and Data Protection</h2>
                            <p>You may make an enquiry for the services either via telephone or through the Website (<strong>“the Enquiry”</strong>) and you agree and acknowledge that where you make an Enquiry via telephone that We may record the conversation for quality, training and order monitoring purposes. By making an Enquiry you agree and acknowledge that you are instructing Us to try and source a vehicle for you and finance to enable you to finance the vehicle and that a contract is formed with regard to these services alone. Unless you expressly request Us not to do so, you agree and acknowledge that by making an Enquiry, We shall commence with the provision of Our services of trying to source a vehicle and finance for you within the statutory cancellation-period, if applicable.</p>
                            <p>If you are applying on behalf of a limited company or other form of corporate entity then you warrant that by making the Enquiry you are duly authorised to do so. Refusal to provide any information requested by Us or a third party in relation to the proposed finance of a vehicle as set out in these Terms shall result in your application being declined and Our services ceasing to be offered to you until such time as you disclose to Us the required information.</p>
                            <p>As part of the submission of the Enquiry you will be prompted to provide Us with various personal data, some of which may be deemed sensitive personal data for the purposes of data protection laws, including (but not limited to) the General Data Protection Regulation 2016 (Regulation (EU) 2016/679), the Data Protection Act 2018 and any replacement for that Act (collectively, <strong>“DP Law”</strong>). You understand and acknowledge that by making an Enquiry you require Us to make enquiries with funders as to the products and services which are available to you and that they and/or We may undertake or arrange credit searches as part of this process. You agree and acknowledge that We shall not be liable to any individual for whom you have disclosed to Us personal information and for whom a credit search is carried out. A record of credit searches may be used by other lenders in assessing future applications by you either through Us or otherwise.</p>
                            <p>All data collected by Us shall be collected and processed fairly and in compliance with DP Law and Our Privacy Policy (as referred to above) We shall be solely responsible as a data controller (as defined in DP Law) for Our compliance with DP Law in relation to Our retention and use of such data. Where you provide Us with the personal data of a third party you warrant that you have received the express consent of that third party to do so.</p>
                            <p>By accepting the Order, you reconfirm that you have read and fully understood Our Privacy Notice.</p>
                            <p>Each party shall keep indemnified the other against any costs, expenses, liabilities, claims, damages, penalties or fines that the other may incur in connection with a breach by the first party of DP Law or associated regulations or these Terms in relation to the collection, sharing or use of personal data in connection with the performance of these Terms save where and to the extent that any such processing of personal data is undertaken at the specific request of the other party.</p>
                            <h2 className="text-mint">4. Prices, the Quotation and Making an Order</h2>
                            <p><span>Prices</span><br />We use a number of industry-leading funding suppliers to provide their pricing. The prices displayed on the Website are an amalgamation of the best prices available at any given time for the vehicles displayed and the available funders. Each funding provider has its own specific financial and operational requirements and these may vary from one funder to the next.</p>
                            <p>Unless otherwise notified by Us to you, all prices include delivery of your desired vehicle to UK mainland locations. You agree and acknowledge that standard delivery shall mean that your desired vehicle shall be driven to its destination unless you specifically request that it be delivered on the back of a trailer in which case We shall notify you of the additional charges applicable.</p>
                            <p>Prices set out on the Website (and which shall subsequently be set out in the Quotation) shall be deemed to:</p>
                            <ul className="list-styled">
                                <li>(a) exclude VAT for business finance, which shall for the avoidance of doubt be additionally charged; or</li>
                                <li>(b) include VAT for personal finances;</li>
                            </ul>
                            <p>with VAT being set to the prevailing national rate from time to time. Should the rate of VAT be adjusted at any time prior to or once a contract is formed between you and Us then the price may be adjusted accordingly.</p>
                            <p>Following receipt of the Enquiry, We shall assess your requirements based on the information that you have provided to Us. You warrant that all of the information that you provide Us with is true and you agree and accept that We are only able to provide Our services in reliance upon the information which you provide Us on that basis.</p>
                            <p>
                            We may, at Our absolute discretion, require you to pay to Us a deposit prior to entering into a contract for the finance of a vehicle as set out below. Deposits shall be required as an expression of interest and on account of any cancellation charges (as detailed below) or the payment of Our processing fee of approximately £165.83 + VAT (equating to £199.00 inclusive of VAT) or that otherwise notified to you, which shall become payable at the order stage.
                            </p>
                            <p>Please note that deposits shall be held in a separate client bank account and are refundable after delivery of the vehicle or, in the event that a contract is not entered into between Us or in the event that you are a Consumer where you cancel a contract in accordance with section 5 below subject to any appropriate deductions being made. Please be aware that when refunding deposits to you in any of the circumstances outlined in this clause, We may at Our absolute discretion retain any processing fee paid by you to Us in reasonable consideration for Our services.</p>
                            <p><span>The Quotation</span><br />We shall use reasonable endeavours to provide you with a quotation for the finance of a vehicle and finance (<strong>“the Quotation”</strong>) within 1 Business Day (being any day which is not a Saturday, Sunday or public holiday in England) of receipt of the Enquiry but for the avoidance of doubt time is not of the essence. The Quotation is not a contractual offer.</p>
                            <p>As stated above, We are reliant on you divulging to Us any and all relevant information and circumstances that may affect the suitability of the Quotation and We will not be held liable to you for any additional requirements that you fail to adequately describe to Us or where you receive an inadequate vehicle as a result of the information which you have provided to Us. If you have any specific requirements in relation to any vehicle then you must notify these to Us as We cannot guarantee the specification of any given model.</p>
                            <p>You agree and acknowledge that meeting the requirements of one funding provider does not necessarily mean that you shall meet the requirements of them all and you are therefore not guaranteed to qualify for the funding which We notify to you in the Quotation. Equally, We do not advise on the respective terms and conditions of any funding offering being made available and you agree and accept that We shall have no responsibility or liability for your ultimate choice.</p>
                            <p><span>Accepting a Quotation</span><br />If you are happy with the options detailed in the Quotation, then you must contact Us by accepting your Quotation online within 10 Business Days of the date of the Quotation to notify Us as such and instruct Us to proceed (<strong>“the Instruction”</strong>). As stated above, the Quotation is not an offer and therefore the Instruction does not give rise to the formation of a contract between you and Us. You are aware that We are dealing with third parties and as such cannot guarantee that the products and services shall remain available as quoted for in the Quotation and We accept no responsibility where this is the case.</p>
                            <p>We may require you to provide Us with such further information as We may require in order to contact the funding providers to try and obtain the required funding for you. You agree and acknowledge that failure to provide Us with any further information required by Us within 10 Business Days of the Quotation will mean that the Quotation no longer remains valid.</p>
                            <p>Upon receipt of the Instruction and such additional information as We may require, We shall liaise directly with the carefully selected finance (from whom you acknowledge that We may receive a commission following from you entering into a contract with them) and vehicle providers with a view to securing the products and services for you as described in the Quotation. However, where We are required to contact funding providers on more than one occasion or where We are required to contact different funding providers than those detailed in the Quotation then you agree and acknowledge that We may contact you again to obtain further information.</p>
                            <p><span>The Order and Accepting an Order</span><br />If We are successful in securing an offer of funding for you and sourcing a vehicle then We shall revert back to you with an order proposal (<strong>“the Order”</strong>) which sets out details of the contract. The Order shall contain details of all charges due to be paid to Us including any arrangement and/or processing fees, which shall in any event already have been outlined to you on the Website prior to receiving the Order.
                            </p>
                            <p>Any arrangement and/or processing fee which We charge is done so in consideration for Our arrangement of any finance agreement which you are required to enter into as per the paragraph below.</p>
                            <p>If you are willing to proceed then a contract shall be formed between you and Us for the supply of the vehicle once We have received the signed Order from you within 10 Business Days of the date of the Order <strong>PROVIDED ONLY THAT</strong> you have entered into a financial agreement with the finance company enabling you to finance the vehicle and you have provided Us with evidence that this has been done. If you sign the Order prior to entering into a contract with the finance company then the contract between you and Us shall not come into force until such time as there is a valid contract in force between you and the finance company.</p>
                            <p>We reserve the right at Our absolute discretion and without liability to you to withdraw or re-issue a Quotation or Order at any time before a contract is formed and may do so for reasons including but not limited to changes in Our standard scale of charges and/or vehicle or funding provider costs and/or changes in legislation.</p>
                            <p>Subject to your statutory rights (specifically those as a Consumer set out below), where you fail to enter into a contract with Us, We reserve the right to charge you for up to 3% of the P11D value of the vehicle, including any options (as set out in the Quotation), in respect of the services provided to date.</p>
                            <h2 className="text-mint">5. Changes, Cancellations and Termination</h2>
                            <p>
                            <span>Changes</span><br />Once a contract has been formed between you and Us, you agree and acknowledge that you will be unable to change or cancel the Order and as such you will not be entitled to a refund for any payment. It is therefore important that you provide Us with accurate information in relation to your requirements and circumstances at all stages as We accept no responsibility where the vehicle provided to you does not meet your actual requirements where these differ from those notified to Us.</p>
                            <p><span>Cancellation</span><br />If you wish to cancel a contract between you and Us for the sourcing of the vehicle then you must notify Us in writing prior to delivery of the vehicle taking place. If you cancel your order, you will be liable for a cancellation fee equivalent to 3% of the P11D value of the vehicle ordered, including any options. This amount is set out in the Quotation and Order, it can also be verified by contacting the vehicle manufacturer. Such cancellation may result in loss of any monies paid by you to Us subject to Our discretion.</p>
                            <p>If you cancel the Order, any processing fee paid will not qualify for a refund if credit has been secured with a finance company, matching the terms of the Order. If credit is approved on different terms, you may be entitled to a refund, or partial refund, of the processing fee.</p>
                            <p><i>The following shall apply <strong>only</strong> if you are a Consumer entering into a regulated finance agreement:</i></p>
                            <p>You may have the right to cancel any contract between you and Us within 14 calendar days without giving any reason. If you do have this right, the cancellation period will expire after 14 calendar days from the date on which you accept the Order. To exercise the right to cancel, you must inform Us of your decision to cancel by a clear statement in writing. To meet the cancellation deadline, it is sufficient for you to send your communication concerning your exercise of the right to cancel before the cancellation period has expired.</p>
                            <p>If you cancel a contract between you and Us, We will (save where set out below) reimburse to you all payments received from you. We will make the reimbursement without undue delay, and not later than 14 calendar days after the day on which We are informed about your decision to cancel. Where possible, We will make the reimbursement using the same means of payment as you used for the initial transaction, unless you have expressly agreed otherwise or We are unable to do so in which case We shall contact you to agree a suitable method of payment. In any event, you will not incur any fees as a result of the reimbursement.</p>
                            <p>If you requested Us to begin the performance of any obligations under a contract between you and Us during the cancellation period (ie, if we have commenced the vehicle-order process), you shall pay Us an amount which is in proportion to what has been performed until you have communicated to Us your cancellation, in comparison with the full coverage of the contract. You agree and acknowledge that We may, at our absolute discretion, deduct such sums as We deem reasonable and in proportion from the deposit which We hold from you to satisfy your obligations in this respect including but not limited to any costs which We have incurred in reliance on your request.</p>
                            <p><span>Termination</span><br />We may immediately terminate (or suspend the performance of Our obligations under) a contract between you and Us at Our absolute discretion and without liability to you in the event that:</p>
                            <ul className="list-styled">
                                <li>(a) you commit a material breach of any term of these Terms which breach is irremediable or (if such breach is remediable) fail to remedy that breach within a period of 10 Business Days after being notified in writing to do so;</li>
                                <li>(b) you commit a breach of any finance agreement entered into in connection with the finance of a vehicle;</li>
                                <li>(c) you suspend, or threaten to suspend, payment of your debts or are unable to pay your debts as they fall due or admit inability to pay your debts or are deemed unable to pay your debts within the meaning of section 123 of the Insolvency Act 1986;</li>
                                <li>(d) you commence negotiations with all or any class of your creditors with a view to rescheduling any of your debts, or make a proposal for or enter into any compromise or arrangement with your creditors other than for the sole purpose of a scheme for a solvent amalgamation with one or more other companies or your solvent reconstruction;</li>
                                <li>(e) a petition is filed, a notice is given, a resolution is passed, or an order is made, for or in connection with your winding up other than for the sole purpose of a scheme for a solvent amalgamation with one or more other companies or your solvent reconstruction;</li>
                                <li>(f) an application is made to court, or an order is made, for the appointment of an administrator, or if a notice of intention to appoint an administrator is given or if an administrator is appointed, over you;</li>
                                <li>(g) the holder of a qualifying floating charge over your assets has become entitled to appoint or has appointed an administrative receiver;</li>
                                <li>(h) a person becomes entitled to appoint a receiver over your assets or a receiver is appointed over your assets;</li>
                                <li>(i) a creditor or encumbrancer of you attaches or takes possession of, or a distress, execution, sequestration or other such process is levied or enforced on or sued against, the whole or any part of your assets and such attachment or process is not discharged within 10 Business Days;</li>
                                <li>(j) you, being an individual, are declared bankrupt or make any arrangement with or for the benefit of your creditors or have a county court administration order made against you under the County Court Act 1984;</li>
                                <li>(k) any event occurs, or proceeding is taken, with respect to you in any jurisdiction to which it is subject that has an effect equivalent or similar to any of the events mentioned in this section;</li>
                                <li>(l) you, being an individual die; or</li>
                                <li>(m) you suspend or cease, or threaten to suspend or cease, carrying on all or a substantial part of your business.</li>
                            </ul>
                            <p>Any provision of these Terms that expressly or by implication are intended to come into or continue in force on or after termination or expiry of a contract between you and Us shall remain in full force and effect. Any such termination shall not affect any rights, remedies, obligations or liabilities of the parties that have accrued up to the date of termination or expiry, including the right to claim damages in respect of any breach of the Terms which existed at or before the date of termination or expiry.</p>
                            <p>You are aware that the provision of finance by the finance provider shall be made under a separate contract and that termination of these Terms are without prejudice to the rights and obligations set out thereunder save where expressly set out. It shall be the responsibility of the finance company to deal with the collection of the vehicle upon termination of your contract with them.</p>
                            <h2 className="text-mint">6. Delivery and Documentation</h2>
                            <p>Unless We otherwise agree in writing We shall not arrange for delivery of the vehicle to be made until such time as:</p>
                            <ul className="list-styled">
                                <li>(a) a contract has been entered into between you and the finance company for the finance of the vehicle as set out in section 4 above;</li>
                                <li>(b) We are satisfied that you hold valid insurance for the vehicle;</li>
                                <li>(c) any and all outstanding charges have been paid by you to Us; and</li>
                                <li>(d) (where applicable), any statutory cooling off periods have expired.</li>
                            </ul>
                            <p>Delivery timescales are provided to you by Us as an indication only and for the avoidance of doubt time for delivery is not of the essence. Whilst We will use reasonable endeavours to ensure that any timescales for delivery are met, We will not be liable to you for any Loss arising out of late delivery.</p>
                            <p>If We are unable to deliver the vehicle including but not limited to where the delivery driver reasonably considers the means of access to your address to be unsafe the vehicle will not be delivered until the means of access is safe. If you are unable, for whatever reason to take delivery of the vehicle or where means of access is unsafe We reserve the right to charge you an additional delivery charge for each subsequent attempted delivery. Such additional charges shall be payable in advance of any further attempts.</p>
                            <p>Once delivery of the vehicle has been made, it is your responsibility to:</p>
                            <ul className="list-styled">
                                <li>(a) read and ensure that you understand any handbooks, warning lights or indicators, instructions or other documentation provided to you with the vehicle;</li>
                                <li>(b) check that the vehicle meets that detailed in the Order; </li>
                                <li>(c) inspect the vehicle for any damages or imperfections; and</li>
                                <li>(d) inform Us immediately of any issues by signing the delivery note containing sufficient details.</li>
                            </ul>
                            <p>By failing to do so you shall be deemed to have accepted the vehicle. Refusal to sign the delivery note may be treated as refusal to take delivery and you may incur additional charges.</p>
                            <h2 className="text-mint">7. Intellectual Property</h2>
                            <p>The content of the Website and Our other literature and the material published on it is protected by copyright, trade marks, database right and other intellectual property rights. You may print one copy, and may download extracts, of any page from the Website for your personal reference and you may draw the attention of others to it provided you keep intact all and any copyright and proprietary notices.</p>
                            <p>Our status (and that of any identified contributors) as the authors of material on the Website must always be acknowledged. You may not otherwise reproduce, modify, copy or distribute or use for commercial purposes any of the materials or content on the Website without written permission from Us.</p>
                            <h2 className="text-mint">8. Liability and Indemnity</h2>
                            <p>Except in respect of death or personal injury caused by Our negligence, and subject to your statutory rights, We shall not be liable for any representation (unless fraudulent), implied warranty, condition or other term, or legal duty for Loss suffered by you whether in contract, tort (including negligence), breach of statutory duty, or otherwise (even if foreseeable) arising out of or in connection with the provision of Our services.</p>
                            <p>In any event, Our entire liability under or in connection with these Terms shall not exceed the charges paid by you to Us in accordance with these Terms, except as expressly provided for in these Terms.</p>
                            <p>You agree to indemnify Us, keep Us indemnified and hold Us harmless against any Loss suffered by Us in connection with these Terms as a result of your breach of the Terms.</p>
                            <h2 className="text-mint">9. General</h2>
                            <p><span>Queries, Complaints, Dispute Resolution and Expert Determination</span><br />We always aim to provide you with the highest standard of service and your Account Manager will always be willing to resolve any queries that you may have. However, if there is any occasion where you are disappointed with the services which We have provided then you may raise a complaint by:</p>
                            <ul className="list-styled">
                                <li>(a) writing to Us at; FAO Compliance Manager, Leasing Options Limited, Options House, Atkin Street, Worsley, Manchester, M28 3DG;</li>
                                <li>(b) emailing Us at <a href="mailto:complaints@leasingoptions.co.uk" className="text-mint">complaints@leasingoptions.co.uk</a>; or</li>
                                <li>(c) calling Us on <a href={`tel:${GetPhoneNumber(isInternal)}`} className="text-mint">{GetPhoneNumber(isInternal)}</a>.</li>
                            </ul>
                            <p>For further details, including how to request an independent review of your complaint, our Complaints Procedure is available on request or on our website via <Link href="/complaints" passHref><a className="text-mint">https://www.leasingoptions.co.uk/complaints</a></Link>.
                            </p>
                            <p><span>Notices</span><br /></p>
                            <ul className="list-unstyled">
                                <li>(a) All notices and communications required to be sent by you shall be made and sent by e-mail to <a href="mailto:info@leasingoptions.co.uk" className="text-mint">info@leasingoptions.co.uk</a> or first class post or hand delivered to Our address as first set out above.</li>
                                <li>(b) All notices and communications required to be sent by Us shall be made and sent by e-mail to the e-mail address or post to the postal address provided to Us by you.</li>
                                <li>(c) If notice is sent in one of the above ways it shall be deemed to have reached the party to whom it is addressed on the next Business Day following the day of posting.</li>
                            </ul>
                            <p><span>Force Majeure</span><br />Both parties will be released from their respective obligations in the event of national emergency, war, prohibitive governmental regulations, import or export regulations or embargoes, strikes, lock-outs or other industrial actions or trade disputes (whether involving Our employees or a third party), difficulties in obtaining raw materials, labour, fuel, parts or machinery, power failure or breakdown in machinery or any other cause beyond the reasonable control of the parties rendering performance of the contract for the provision of Our services impossible provided that this condition shall only have effect at Our discretion except when such event renders performance impossible for a continuous period of 2 (two) calendar months.</p>
                            <p><span>Third Parties</span><br />Except as otherwise specified in the Terms, it is the intention of the parties that no person not a party to the Terms shall have any rights in relation to it under the Contracts (Rights of Third Parties) Act 1999.</p>
                            <p><span>Entire Agreement</span><br />These Terms set out the entire agreement between the parties in connection with its subject matter and neither party has entered into these Terms in reliance on any warranty, representation or statement made by the other (which for the avoidance of any doubt includes but is not limited to any verbal discussions between the parties) which is not set out in these Terms. Nothing in these Terms purports to exclude liability for any fraudulent statement or act.</p>
                            <p><span>Waiver &amp; Severability</span><br />In the event that any provision of these Terms or any part of such is declared by any judicial or other competent authority to be void, voidable, illegal or otherwise unenforceable or indication of the same are received by either of the parties from any relevant competent authority the parties shall amend the relevant part of that clause in such reasonable manner as achieves the intention of the parties without illegality or at Our discretion that part of the relevant provisions may be severed from these Terms in which event the remaining Terms and the remaining part of the relevant condition shall remain in full force and effect.</p>
                            <p>The failure of either party at any time or times to require performance of any provision hereof shall not affect that party's right to enforce such provision at a later time. No waiver by either party of any conditions or the breach of any term covenant representation or warranty contained in these Terms in any one or more instances shall be deemed to be or construed as a further or continuing waiver of any such condition or breach or a waiver of any other condition or be deemed to be or construed as a waiver of the breach of any other term covenant representation or warranty in these Terms.</p>
                            <p><span>Governing Law and Jurisdiction</span><br />These Terms are governed by the English law in every particular including formation and interpretation and shall be deemed to have been made in England. Any proceedings arising out of or in connection with the Website or the Order may be brought in any court of competent jurisdiction in England and Wales.</p>
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
}

TermsConditions.layout = MainLayout;

const mapStateToProps = (state) => ({
    isInternal: state.isInternal
});

export default connect(mapStateToProps)(TermsConditions);